### ISSUE TITLE
Blurry background behind body of text

### ISSUE THREAD

**Issue by apatel762** [apatel762/backlinks#35]
it'll probably look cool

could use the CSS-only example from [this codepen](https://codepen.io/hylobates-lar/pen/qBbQeON) for the colourful blurry background and then something else for the body?

```CSS
html, body {
  width: 100%;
  height:100%;
}

body {
    background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
    background-size: 400% 400%;
    animation: gradient 15s ease infinite;
}

@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
}
```
